@startuml ClassDiagram

package Nmeasoft {

  file servers.json [
    file servers.json 
    {{json
      {
        "servers" : [
          {
            "serverId" : 1,
            "port" : 10100,
            "description" : "GPS-Server"
          },
          {
            "serverId" : 2,
            "port" : 10200,
            "description" : "RAR-Server"
          }
        ],
        "lastUpdate" : "21072023"
      }
    }}
  ]

  file devices.json [
    file devices.json 
    {{json
      {
        "devices" : [
          {
            "deviceId" : 1,
            "name" : "GPS-1",
            "deviceType" : "GPS",
            "sentences" : [
              "GGA",
              "GLL",
              "RMC",
              "ZDA"
            ],
            "interval" : 2,
            "isAddChecksum" : true,
            "serverId" : 1
          },
          {
            "deviceId" : 2,
            "name" : "RAR-1",
            "deviceType" : "RAR",
            "sentences" : [
              "TLL",
              "TTM"
            ],
            "interval" : 1,
            "isAddChecksum" : false, 
            "serverId" : 2
          }
        ],
        "lastUpdate" : "21072023"
      }
    }}
  ]

  database redis {
    folder nmeaobjects {

    } 
  }

  enum DeviceType {
    AIS
    CUSTOM 
    GPS 
    RAR 
  }

  enum GpsSentence {
    GGA
    GLL
    RMC
    ZDA
  }

  enum RarSentence {
    TLL
    TTL 
  }

  enum AisSentence {
    VDM  
    VDO 
  }

  class Module {
    -Servers : List<Server>
    -Devices : List<Device>
    -loadServers() : void
    -loadDevices() : void
    -loadObjects() : void 
    -run() : void
  }

  class Server {
    -ServerId : Int 
    -Ip : String 
    +Port : Int
    +Description : String 
    +DeviceIds : List<String> 
    +Server(ip, port)
    +start() : Boolean
    +stop() : void 
    +response(sentence : String) : void
    +onNewConnection() : void
  }

  class Position {
    +Latitude : Double
    +Longitude : Double
    +Altitude : Double
  }

  abstract class NmeaObject {
    ~Position : Position
    ~Course : Double 
    ~Speed : Double 
    ~LastUpdate : DateTime
    ~DeviceId : Int  
  }

  class GpsObject {
    SatelitesUsed : Int 
  }

  class AisObject {
    +MMSI : String 
    +ShipName : String 
    +Destination : String
    +CallSign : String 
    +IMO : String
    +ETA : DateTime 
  }

  class RarObject {
    +TrackNumber : Int 
    +TrackName : String 
    +Status : Int 
    +DistanceFromGps : Double 
    +BearingFromGps : Double 
  }

  abstract class Device {
    ~DeviceId : Int
    ~Name : String 
    ~Interval : Int
    ~DeviceType : DeviceType
    ~IsAddChecksum : Boolean
    ~ServerId : Int 
    ~Timer : Timer
    ~Server : Server
    -onTimeOut() : void 
    -addChecksum(data: String) : String
    +generateSentence() : void 
  }

  class AisDevice {
    +Sentences : List<AisSentence>
    +AisObject : NmeaObject
  }
  
  class CustomDevice {
    +Sentences : List<String>
  }

  class GpsDevice {
    +Sentences : List<GpsSentence>
    +GpsObject : NmeaObject
  }

  class RarDevice {
    +Sentences : List<RarSentence>
    +RarObject : NmeaObject
  }


  Module o-- servers.json
  Module o-- devices.json 
  Module o-- redis
  Module *-- Server
  Module *-- Device

  Server "0..*" -- "1..1" Device : contain

  NmeaObject *-- Position
  NmeaObject <|-- GpsObject
  NmeaObject <|-- RarObject
  NmeaObject <|-- AisObject

  Device *-- DeviceType
  Device <|-- AisDevice
  Device <|-- CustomDevice
  Device <|-- GpsDevice
  Device <|-- RarDevice

  GpsDevice *-- NmeaObject
  RarDevice *-- NmeaObject
  AisDevice *-- NmeaObject
  GpsDevice *-- GpsSentence
  RarDevice *-- RarSentence
  AisDevice *-- AisSentence
}

@enduml